services:
        op25-boatbod:
                build: .
                ports:
                        - "8888:8888"
                devices:
                        - "/dev/snd"
                        - "/dev/bus/usb"
                volumes:
                        - "/tmp:/tmp"
                        #- "/opt/op25_config/asound.conf:/etc/asound.conf"
                        - "/opt/op25_config:/config"
                        - "/opt/op25_config/mpscs.tsv:/op25/op25/gr-op25_repeater/apps/mpscs.tsv"
                        - "/opt/op25_config/suid.tsv:/op25/op25/gr-op25_repeater/apps/suid.tsv"

#                privileged: true
                dns: 8.8.8.8
                restart: unless-stopped
                entrypoint: /bin/bash /config/rx.sh  
